### ISSUE TITLE
Infinite scroll

### ISSUE THREAD

**Issue by SaFrMo** [funkhaus/vuehaus#75]
Possibly use https://github.com/ElemeFE/vue-infinite-scroll

**Comment by SaFrMo** [comment]
@drewbaker @jrobson153 @lwaldner Looking at the [vue-infinite-scroll directive](https://github.com/ElemeFE/vue-infinite-scroll) Drew found, I think that's definitely the way to go. The first time one of us uses it in production, let's post a link to the code here and figure out a generalized function from that - then we could copy it into a snippet or gist and refer to it when needed.

**Comment by drewbaker** [comment]
I'd like to add this to the archive page by default. We need it on every site pretty much. We need it on Ridley Scott already (and that uses Masonry too, so it has to work with that).

**Comment by SaFrMo** [comment]
Added in c8abde2!
