### ISSUE TITLE
Installation error with node 8.x

### ISSUE THREAD

**Issue by mrfrancescomoro** [funkhaus/vuehaus#93]
Hello,
this is not really an issue but just a warning.
Vuepress installation is not currently working on node 8.*

I downgraded node to 6.0 and the installation and everything works perfectly but when I launch npm run dev on windows via cmd I got this error:

![errore](https://user-images.githubusercontent.com/2639793/38354953-b07d4f54-38bb-11e8-8926-be06ba3b2823.jpg)

in case you were wondering
**"rm" non è riconosciuto come comando interno o esterno, un programma eseguibile o un file batch."**
means:
**"rm" is not recognised as an internal or external command, an executable program or a batch file**

Using Git.bash terminal everything seems to work fine.

These info could be a great helping-hand to a node/npm newbie.

Btw I love what you guys did here!
Thanks

**Comment by johndigital** [comment]
Thank you for the feedback @mrfrancescomoro this is very helpful!

@safrmo I think maybe the shell wrapper mentioned in this SO reply could solve this issue but it will be hard for us to test: https://stackoverflow.com/questions/48120889/cross-platform-rm-command

**Comment by SaFrMo** [comment]
Agreed, thanks @mrfrancescomoro, this is excellent feedback!

I'll take a look at the wrapper @johndigital mentioned as well as [rimraf](https://github.com/isaacs/rimraf) later on today and see if those are better solutions. Good catch!

**Comment by mrfrancescomoro** [comment]
no problem @johndigital and @SaFrMo always happy to help where it's possibile!

**Comment by SaFrMo** [comment]
I just pushed 46af6a1, which updates `npm run clean` to run `npx rimraf static/bundle.*`, which should do the same thing as before while working cross-platform. 

I couldn't replicate the installation bug with node 8.x - @mrfrancescomoro, do you know which exact version of node you were using? Thanks!

**Comment by mrfrancescomoro** [comment]
I'm not sure if it was the 8.9.1 or the 8.11.1
I have both installed and i do not remember which one I was using.
Sorry.

**Comment by SaFrMo** [comment]
No problem, I'll give them both a look!

**Comment by SaFrMo** [comment]
The installation worked fine for me using both the versions you mentioned - I'll edit the title of this issue and mark it as "holding" just in case anyone comes across it in the future. Let us know if it happens again at all and we'll make a note in the readme. Thanks again!

**Comment by SaFrMo** [comment]
Marking as complete since we haven't run into this since then - let me know if I should reopen!
